services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  travel-agency:
    build: travel-agency
    ports:
      - "8060:8060"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8060/"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 3s       
    depends_on:
      - db
  recommendations:
    build: mcp-amadeus
    ports:
      - "8080:8080"
    env_file: mcp-amadeus/.env
  client:
    build: mcp-client
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      recommendations:
        condition: service_started
      db:
        condition: service_started
      travel-agency:
        condition: service_healthy
        restart: true
    extra_hosts:
      - "host.docker.internal:host-gateway"   
